-- MySQL Script generated by MySQL Workbench
-- Tue May 10 19:38:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotelms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelms` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hotelms` ;

-- -----------------------------------------------------
-- Table `hotelms`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`services` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`services` (
  `id_service` INT NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price_hourly` FLOAT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`booking_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`booking_services` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`booking_services` (
  `id_booking_services` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `id_service` INT NOT NULL,
  `start_date` TIMESTAMP NOT NULL,
  `end_date` TIMESTAMP NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_booking_services`),
  INDEX `id_service` (`id_service` ASC) VISIBLE,
  CONSTRAINT `booking_services_ibfk_1`
    FOREIGN KEY (`id_service`)
    REFERENCES `hotelms`.`services` (`id_service`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`departments` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`departments` (
  `id_department` INT NOT NULL,
  `dept_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_department`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`guest` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`guest` (
  `id_guest` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(70) NOT NULL,
  `address` VARCHAR(300) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_guest`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`roomtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`roomtype` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`roomtype` (
  `id_room_type` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_room_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`room` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`room` (
  `id_room` INT NOT NULL,
  `status` ENUM('Wolny', 'Zajęty') NOT NULL,
  `room_number` VARCHAR(6) NOT NULL,
  `price` FLOAT NOT NULL,
  `id_room_type` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id_room`),
  INDEX `id_room_type` (`id_room_type` ASC) VISIBLE,
  CONSTRAINT `room_ibfk_1`
    FOREIGN KEY (`id_room_type`)
    REFERENCES `hotelms`.`roomtype` (`id_room_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`reservation` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`reservation` (
  `id_reservation` INT NOT NULL AUTO_INCREMENT,
  `check_in` DATETIME NOT NULL,
  `check_out` DATETIME NULL DEFAULT NULL,
  `adults` INT NULL DEFAULT NULL,
  `children` INT NULL DEFAULT NULL,
  `bill` FLOAT NULL DEFAULT NULL,
  `id_guest` INT NOT NULL,
  `id_room` INT NOT NULL,
  PRIMARY KEY (`id_reservation`),
  INDEX `id_room` (`id_room` ASC) VISIBLE,
  INDEX `reservation_ibfk_1_idx` (`id_guest` ASC) VISIBLE,
  CONSTRAINT `reservation_ibfk_1`
    FOREIGN KEY (`id_guest`)
    REFERENCES `hotelms`.`guest` (`id_guest`),
  CONSTRAINT `reservation_ibfk_2`
    FOREIGN KEY (`id_room`)
    REFERENCES `hotelms`.`room` (`id_room`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`payment` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`payment` (
  `id_payment` INT NOT NULL,
  `id_guest` INT NOT NULL,
  `id_reservation` INT NOT NULL,
  `type` ENUM('Karta płatnicza', 'Gotówka', 'BLIK') NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_payment`),
  INDEX `id_reservation` (`id_reservation` ASC) VISIBLE,
  INDEX `payment_ibfk_1_idx` (`id_guest` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`id_guest`)
    REFERENCES `hotelms`.`guest` (`id_guest`),
  CONSTRAINT `payment_ibfk_2`
    FOREIGN KEY (`id_reservation`)
    REFERENCES `hotelms`.`reservation` (`id_reservation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`workers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`workers` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`workers` (
  `id_worker` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(70) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `id_department` INT NOT NULL,
  PRIMARY KEY (`id_worker`),
  INDEX `id_department` (`id_department` ASC) VISIBLE,
  CONSTRAINT `workers_ibfk_1`
    FOREIGN KEY (`id_department`)
    REFERENCES `hotelms`.`departments` (`id_department`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`room_service_tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`room_service_tasks` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`room_service_tasks` (
  `id_room_service_tasks` INT NOT NULL,
  `1` TEXT NULL DEFAULT NULL,
  `2` TEXT NULL DEFAULT NULL,
  `3` TEXT NULL DEFAULT NULL,
  `4` TEXT NULL DEFAULT NULL,
  `5` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_room_service_tasks`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`room_service_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`room_service_types` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`room_service_types` (
  `id_room_service_type` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `id_tasks` INT NOT NULL,
  PRIMARY KEY (`id_room_service_type`),
  INDEX `id_tasks` (`id_tasks` ASC) VISIBLE,
  CONSTRAINT `room_service_types_ibfk_1`
    FOREIGN KEY (`id_tasks`)
    REFERENCES `hotelms`.`room_service_tasks` (`id_room_service_tasks`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`room_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`room_service` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`room_service` (
  `id_room_service` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `id_department` INT NOT NULL,
  `id_worker` INT NULL DEFAULT NULL,
  `id_room` INT NOT NULL,
  `id_room_service_type` INT NOT NULL,
  PRIMARY KEY (`id_room_service`),
  INDEX `id_department` (`id_department` ASC) VISIBLE,
  INDEX `id_worker` (`id_worker` ASC) VISIBLE,
  INDEX `id_room` (`id_room` ASC) VISIBLE,
  INDEX `id_room_service_type` (`id_room_service_type` ASC) VISIBLE,
  CONSTRAINT `room_service_ibfk_1`
    FOREIGN KEY (`id_department`)
    REFERENCES `hotelms`.`departments` (`id_department`),
  CONSTRAINT `room_service_ibfk_2`
    FOREIGN KEY (`id_worker`)
    REFERENCES `hotelms`.`workers` (`id_worker`),
  CONSTRAINT `room_service_ibfk_3`
    FOREIGN KEY (`id_room`)
    REFERENCES `hotelms`.`room` (`id_room`),
  CONSTRAINT `room_service_ibfk_4`
    FOREIGN KEY (`id_room_service_type`)
    REFERENCES `hotelms`.`room_service_types` (`id_room_service_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelms`.`services_guests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelms`.`services_guests` ;

CREATE TABLE IF NOT EXISTS `hotelms`.`services_guests` (
  `id_guest` INT NOT NULL,
  `id_booking_services` INT NOT NULL,
  PRIMARY KEY (`id_guest`, `id_booking_services`),
  INDEX `id_booking_services` (`id_booking_services` ASC) VISIBLE,
  CONSTRAINT `services_guests_ibfk_1`
    FOREIGN KEY (`id_booking_services`)
    REFERENCES `hotelms`.`booking_services` (`id_booking_services`),
  CONSTRAINT `services_guests_ibfk_2`
    FOREIGN KEY (`id_guest`)
    REFERENCES `hotelms`.`guest` (`id_guest`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
